version: '3.9'

services:
  postgres:
    image: postgres:latest
    volumes:
      - db_data:/var/lib/postgres
    restart: always
    ports:
      - "5432:5432"
    expose:
      - "5432"
    env_file:
      - config/db-prod.env

volumes:
  db_data: {}